### ISSUE TITLE
Mod Request: BrownBug's Redstone Mod

### ISSUE THREAD

**Issue by SamBugBrown** [NinjaKap/TechnologyAdvanced-II#15]
Please Add BrownBug's Redstone Mod to the pack. The link is available here: [https://mcreator.pylo.co/modification/19043/brownbugs-redstone-mod]

Thanks!
SamBugBrown

**Comment by NinjaKap** [comment]
MCreator Mods aren't supported in TechnologyAdvanced, due to the Item IDs.
